
import { Language } from './types';

export const STRINGS = {
  [Language.AR]: {
    appName: 'TalibSpace',
    welcome: 'مرحبا بيك فـ فضاء طلبة CMC',
    login: 'دخول',
    signup: 'تسجيل',
    studentOnly: 'هاد الفضاء حصري لطلبة CMC فقط',
    feed: 'الرئيسية',
    resources: 'دروس',
    opportunities: 'فرص',
    random: 'تواصل عشوائي',
    profile: 'بروفايل',
    announcements: 'إعلانات',
    activities: 'أنشطة',
    messages: 'رسائل',
    groups: 'مجموعات',
    live: 'مباشر',
    aiAssistant: 'مساعد AI',
    postSomething: 'شارك شي حاجة مع خوتك...',
    post: 'نشر',
    like: 'عجبني',
    comment: 'تعليق',
    logout: 'خروج',
    searching: 'كنقلبو ليك على شي حد...',
    startCall: 'بدا مكالمة عشوائية',
    skip: 'التالي',
    end: 'قطع',
    report: 'تبليغ',
    matched: 'لقينا ليك واحد الطالب من CMC!',
    safetyNotice: 'هاد الفضاء آمن، أي تصرف غير لائق كيعرضك للطرد النهائي.',
    internships: 'تدريبات',
    jobs: 'فرص عمل',
    urgent: 'عاجل',
    trips: 'رحلات',
    sports: 'رياضة',
    join: 'شارك',
    joined: 'مشارك',
    allFilieres: 'جميع التخصصات',
    call: 'اتصال',
    videoCall: 'مكالمة فيديو',
    audioCall: 'مكالمة صوتية',
    joinCall: 'دخول للمكالمة',
    ongoingCall: 'مكالمة جارية...',
    points: 'نقطة',
    level: 'المستوى',
  },
  [Language.FR]: {
    appName: 'TalibSpace',
    welcome: 'Bienvenue sur TalibSpace CMC',
    login: 'Connexion',
    signup: 'Inscription',
    studentOnly: 'Espace exclusif aux étudiants CMC',
    feed: 'Accueil',
    resources: 'Cours',
    opportunities: 'Opportunités',
    random: 'Connect',
    profile: 'Profil',
    announcements: 'Annonces',
    activities: 'Activités',
    messages: 'Messages',
    groups: 'Groupes',
    live: 'En Direct',
    aiAssistant: 'Assistant AI',
    postSomething: 'Partagez avec vos collègues...',
    post: 'Publier',
    like: "J'aime",
    comment: 'Commenter',
    logout: 'Déconnexion',
    searching: 'Recherche d\'un partenaire...',
    startCall: 'Lancer un appel aléatoire',
    skip: 'Suivant',
    end: 'Terminer',
    report: 'Signaler',
    matched: 'Vous avez été matché avec un étudiant !',
    safetyNotice: 'Espace sécurisé. Tout comportement inapproprié entraîne un ban.',
    internships: 'Stages',
    jobs: 'Emplois',
    urgent: 'Urgent',
    trips: 'Voyages',
    sports: 'Sports',
    join: 'Rejoindre',
    joined: 'Inscrit',
    allFilieres: 'Toutes les filières',
    call: 'Appeler',
    videoCall: 'Appel Vidéo',
    audioCall: 'Appel Audio',
    joinCall: 'Rejoindre l\'appel',
    ongoingCall: 'Appel en cours...',
    points: 'Points',
    level: 'Niveau',
  },
  [Language.EN]: {
    appName: 'TalibSpace',
    welcome: 'Welcome to TalibSpace CMC',
    login: 'Login',
    signup: 'Sign Up',
    studentOnly: 'Exclusive for CMC Students only',
    feed: 'Home',
    resources: 'Courses',
    opportunities: 'Opportunities',
    random: 'Random Connect',
    profile: 'Profile',
    announcements: 'Announcements',
    activities: 'Activities',
    messages: 'Messages',
    groups: 'Groups',
    live: 'Live Events',
    aiAssistant: 'AI Buddy',
    postSomething: 'Share something with the squad...',
    post: 'Post',
    like: 'Like',
    comment: 'Comment',
    logout: 'Logout',
    searching: 'Searching for a match...',
    startCall: 'Start Random Call',
    skip: 'Skip',
    end: 'End',
    report: 'Report',
    matched: 'Found a CMC Student!',
    safetyNotice: 'Safe space. Inappropriate behavior results in a permanent ban.',
    internships: 'Internships',
    jobs: 'Jobs',
    urgent: 'Urgent',
    trips: 'Trips',
    sports: 'Sports',
    join: 'Join',
    joined: 'Joined',
    allFilieres: 'All Specialties',
    call: 'Call',
    videoCall: 'Video Call',
    audioCall: 'Audio Call',
    joinCall: 'Join Call',
    ongoingCall: 'Ongoing Call...',
    points: 'Points',
    level: 'Level',
  }
};

export const MOCK_POSTS = [
  {
    id: '1',
    authorId: 'u1',
    authorName: 'Mehdi Bennani',
    authorAvatar: 'https://i.pravatar.cc/150?u=mehdi',
    content: 'Drari, shkun 3endo résumé dyal Python? 🐍 Imtihan 9reb!',
    timestamp: '2h ago',
    likes: 12,
    comments: [],
    type: 'question'
  },
  {
    id: '2',
    authorId: 'u2',
    authorName: 'Salma El Amrani',
    authorAvatar: 'https://i.pravatar.cc/150?u=salma',
    content: 'Huge internship opportunity in Casablanca at OCP. Check the resources tab! 🚀',
    timestamp: '5h ago',
    likes: 24,
    comments: [],
    type: 'advice'
  }
];

export const MOCK_ANNOUNCEMENTS = [
  { id: 'a1', title: 'Exam Schedule Update', content: 'Python exam moved to next Monday 9:00 AM.', type: 'urgent', filiere: 'Digital', date: 'Today' },
  { id: 'a2', title: 'Cybersecurity Seminar', content: 'OCP experts visiting campus tomorrow at 2PM.', type: 'event', filiere: 'All', date: 'Tomorrow' },
];

export const MOCK_ACTIVITIES = [
  { id: 'act1', title: 'Trip to Ifrane', description: 'Weekend rihla! Skiing and chilling. Limited spots. 🏔️', type: 'Trip', date: 'Feb 20', location: 'Ifrane', participants: 35, maxParticipants: 50, isJoined: false },
  { id: 'act2', title: 'Football Tournament', description: 'Inter-filière cup. Who wins the trophy? 🏆', type: 'Sport', date: 'Feb 15', location: 'Campus Field', participants: 80, maxParticipants: 100, isJoined: true },
];

export const MOCK_RESOURCES = [
  { id: 'r1', title: 'Python Basics 2024', description: 'Full guide for beginners and intermediates.', specialty: 'Digital', fileType: 'PDF', sharedBy: 'Mehdi', downloads: 145 },
  { id: 'r2', title: 'Industrial Automation', description: 'Diagnostic techniques for Siemens PLCs.', specialty: 'Industrie', fileType: 'DOCX', sharedBy: 'Anas', downloads: 89 },
];

export const MOCK_LIVE_EVENTS = [
  { id: 'l1', title: 'How to Land an Internship', host: 'Prof. Alami', viewers: 124, thumbnail: 'https://picsum.photos/seed/live1/400/225', isLive: true },
  { id: 'l2', title: 'UI/UX Design Workshop', host: 'Salma El Amrani', viewers: 45, thumbnail: 'https://picsum.photos/seed/live2/400/225', isLive: true },
];

export const MOCK_CHATS = [
  { id: 'c1', partnerName: 'Yassine', partnerAvatar: 'https://i.pravatar.cc/150?u=yass', lastMessage: 'Shof hadak l-lien dyal Python.', unread: true },
  { id: 'c2', partnerName: 'Kanza', partnerAvatar: 'https://i.pravatar.cc/150?u=kanz', lastMessage: 'Thank you for the notes!', unread: false },
];
